Setup GOPATH given necessary env variables

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -60,24 +60,7 @@ if [ -e "${build}/bin" -a ! -d "${build}/bin" ]; then
 fi
 
 ensureGo "${ver}"
-
 mkdir -p "${build}/bin"
-
-# If $GO_LINKER_SYMBOL and GO_LINKER_VALUE are set, tell the linker to DTRT
-FLAGS=(-tags heroku)
-if [ -n "${GO_LINKER_SYMBOL}" -a -n "${GO_LINKER_VALUE}" ]; then
-    case "${ver}" in
-        go1.0*|go1.1*|go1.2*|go1.3*|go1.4*)
-            xval="${GO_LINKER_SYMBOL} ${GO_LINKER_VALUE}"
-        ;;
-        *)
-            xval="${GO_LINKER_SYMBOL}=${GO_LINKER_VALUE}"
-        ;;
-    esac
-    FLAGS=(${FLAGS[@]} -ldflags "-X ${xval}")
-fi
-
-export GOPATH
 
 if [ -n "${src}" -a "${src}" != "${build}" -a -e "${src}/Procfile" ]; then
     mv -t "${build}" "${src}/Procfile"
@@ -101,9 +84,11 @@ if [ "${GO_INSTALL_TOOLS_IN_IMAGE}" = "true" ]; then
 fi
 
 if [ "${GO_SETUP_GOPATH_IN_IMAGE}" = "true" ]; then
-    start "Cleaning up \$GOPATH/pkg"
-        rm -rf $GOPATH/pkg
-    finished
-    echo 'export GOPATH=$HOME' > "${build}/.profile.d/zzgopath.sh"  #Try to make sure it's down in towards the end
-    echo 'cd $GOPATH/src/'${name} >> "${build}/.profile.d/zzgopath.sh" # because of this
+    if [ -z "${GO_INSTALL_PACKAGE_SPEC}" ]; then
+        echo "Missing GO_INSTALL_PACKAGE_SPEC"
+        exit 1
+    fi
+    export GOPATH="${build}/src/${GO_INSTALL_PACKAGE_SPEC}"
+    mkdir -p ${GOPATH}
+    mv ${build}/* ${GOPATH}
 fi
