Put back setupGOPATH func

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -74,6 +74,22 @@ cd $build
 mkdir -p $build/.profile.d
 echo 'PATH=$PATH:$HOME/bin' > $build/.profile.d/go.sh
 
+setupGOPATH() {
+    local name="${1}"
+    local t="$(mktemp -d)"
+
+    cp -R ${build}/* ${t}
+    GOPATH="${t}/.go"
+    export GOBIN="${build}/bin"
+
+    local src="${GOPATH}/src/${name}"
+    mkdir -p "${src}"
+    mkdir -p "${build}/bin"
+    mv -t "${src}" "${t}"/*
+
+    export GOPATH=${GOPATH}
+}
+
 if [ "${GO_INSTALL_TOOLS_IN_IMAGE}" = "true" ]; then
     start "Copying go tool chain to \$GOROOT=\$HOME/.heroku/go"
         mkdir -p "${build}/.heroku/go"
@@ -83,12 +99,8 @@ if [ "${GO_INSTALL_TOOLS_IN_IMAGE}" = "true" ]; then
     finished
 fi
 
-if [ "${GO_SETUP_GOPATH_IN_IMAGE}" = "true" ]; then
-    if [ -z "${GO_INSTALL_PACKAGE_SPEC}" ]; then
-        echo "Missing GO_INSTALL_PACKAGE_SPEC"
-        exit 1
-    fi
-    export GOPATH="${build}/src/${GO_INSTALL_PACKAGE_SPEC}"
-    mkdir -p ${GOPATH}
-    mv ${build}/* ${GOPATH}
+if [ -z "${GO_INSTALL_PACKAGE_SPEC}" ]; then
+    echo "Missing GO_INSTALL_PACKAGE_SPEC"
+    exit 1
 fi
+setupGOPATH ${GO_INSTALL_PACKAGE_SPEC}
